<h2>Editar Post</h2>

<?php
/**
 * @var $form \Zend\Form\Form
 */
$form = $this->form;

$this->formElementErrors()
    ->setMessageOpenFormat('<p class="text-danger">')
    ->setMessageCloseString('</p>')
    ->render($form);

$form->setAttribute('action',
    $this->url('post/default', array('controller' => 'post', 'action' => 'editar', 'id' => $this->id)));

$form->prepare();

echo $this->form()->openTag($form);

echo $this->formCollection($form);

echo $this->form()->closeTag();
?>

<style type="text/css">
    input, textarea, label, select {
        display: block;
    }
</style>