<h2>Editar Post</h2>

<?php
/**
 * @var $form \Zend\Form\Form
 */
$form = $this->form;


$strMessage = "";
$strMessageType = "";
if ($this->flashMessenger->hasSuccessMessages()) {
    $strMessage = $this->flashMessenger()->getSuccessMessages();
    $strMessageType = 'success';
}
if ($this->flashMessenger->hasErrorMessages()) {
    $strMessage = $this->flashMessenger()->getErrorMessages();
    $strMessageType = 'danger';
}
if (strlen($strMessage[0])) {
    echo '<div class="alert alert-' . $strMessageType . '">'
        . $strMessage[0] .
        '<button type="button" class="close" data-dismiss="alert">×</button></div>';
}

$this->formElementErrors()
    ->setMessageOpenFormat('<div class="alert alert-danger"><button type="button" class="close" data-dismiss="alert">×</button>')
    ->setMessageCloseString('</div>')
    ->render($form);

$form->setAttribute('action',
    $this->url('post/default', array('controller' => 'post', 'action' => 'editar', 'id' => $this->id)));

$form->prepare();

echo $this->form()->openTag($form);

echo $this->formCollection($form);

echo $this->form()->closeTag();
?>

<style type="text/css">
    input, textarea, label, select {
        display: block;
    }
</style>