<a class="btn btn-success"
   href="<?php echo $this->url('categoria/default', array('controller' => 'categoria', 'action' => 'inserir')); ?>">Cadastar</a>
<hr>

<h1>Todas as categorias</h1>

<table class="table table-bordered table-striped table-hover table-condensed">
    <thead>
    <tr>
        <th>ID</th>
        <th>NOME</th>
        <th>AÇÃO</th>
    </tr>
    </thead>
    <tbody>
    <?php
    /**
     * @var $entity \Categoria\Entity\Category
     */
    ?>
    <?php if ($this->data): ?>
        <?php foreach ($this->data as $entity): ?>
            <tr>
                <td><?php echo $entity->getId(); ?></td>
                <td><?php echo $entity->getNome(); ?></td>
                <td>
                    <a class="btn btn-success" href="<?php echo $this->url('categoria/default',
                        array('controller' => 'categoria', 'action' => 'editar', 'id' => $entity->getId())); ?>"><i
                            class="glyphicon glyphicon-pencil"></i> </a>
                    <a class="btn btn-danger" href="<?php echo $this->url('categoria/default',
                        array('controller' => 'categoria', 'action' => 'excluir', 'id' => $entity->getId())); ?>"><i
                            class="glyphicon glyphicon-remove-sign"></i> </a>
                </td>
            </tr>
        <?php endforeach; ?>
    <?php else: ?>
        <p>Nenhum registro encontrado!</p>
    <?php endif; ?>


    </tbody>
</table>